### ISSUE TITLE
Errors while running the script

### ISSUE THREAD

**Issue by Yatendrasinghranawat** [davidpendergast/watermark-remover#1]
C:\Users\YATENDRA\Desktop\w>python test_gen.py
Traceback (most recent call last):
  File "test_gen.py", line 9, in <module>
    wm_image = wm_remover.get_image(directory, "wm.png", mode="RGBA")
  File "C:\Users\YATENDRA\Desktop\w\wm_remover.py", line 60, in get_image
    img = Image.open(directory + name)
AttributeError: module 'PIL.Image' has no attribute 'open'

C:\Users\YATENDRA\Desktop\w>python img_scraper.py
Traceback (most recent call last):
  File "img_scraper.py", line 35, in <module>
    num_to_grab = int(sys.argv[1])
IndexError: list index out of range

C:\Users\YATENDRA\Desktop\w>python wm_remover.py
Traceback (most recent call last):
  File "wm_remover.py", line 311, in <module>
    root_dir = args[1]
IndexError: list index out of range

**Comment by davidpendergast** [comment]
This wasn't really designed for general use - I wrote it for fun to operate on a specific dataset I had on-hand. It's likely going to be more trouble than it's worth trying to get it to run on your system.

That being said, img_scraper.py and wm_remover.py take arguments. There's documentation at the top of those files describing what the arguments are. img_scraper.py also relies on the existence of a very specific online image database, which may or may not exist anymore. You'll also need to have PIL (Python Imaging Library) installed on your system.

**Comment by yatendra3192** [comment]
I also have a specific dataset of 2000 images with the same watermark on same please can you help me how can I use your technique to get the result you have shown?
